### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by daviddiazvico** [comment]
I like the idea, but why this particular config? Since there might be some non-Python files in the repo, why not something like this?

root = true

[*]
charset=utf-8
end_of_line = lf
insert_final_newline = false

[*.py]
indent_style = space
indent_size = 4

**Comment by KOLANICH** [comment]
How about
```ini
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = false
indent_size = 4
indent_style = tab

[*.py]
indent_style = space
```
?

**Comment by daviddiazvico** [comment]
Good, update the file and I'll merge.

**Comment by KOLANICH** [comment]
Reordered the lines to minimize the diff and added `root = true`

**Pull request merged**
