### PR TITLE
Add return_X_y parameter to all fetchers.

### PR DESCRIPTION
**Pull request by vnmabus**
Adds a `return_X_y` parameter to all fetchers, that allows them to return a tuple with only the data and target. This is an option that was added to the scikit-learn interface for fetchers in https://github.com/scikit-learn/scikit-learn/issues/6670.

### CODE REVIEW

**Comment by daviddiazvico** [comment]
Nice

**Comment by vnmabus** [comment]
Is there any problem with this? The forex failures are unrelated.

**Comment by vnmabus** [comment]
In fact, the Forex failure is because of this issue: https://github.com/apiforfun/theforexapi/issues/5

**Comment by daviddiazvico** [comment]
Sorry, I just forgot this. It's fine.

**Pull request merged**
